Repository subhadipbhowmik/bio-branch, pull requests merged in 2024-10, with the labels that each got.

#20 # ### Feature Request: I would like to propose adding a "Contact Us" tab to the main navigation bar to improve user interaction and support.
  site/components/Footer.js
Labels: gssoc-ext, gssoc, hacktoberfest-accepted, level1

#21 Updated README.md #19
  README.md
Labels: gssoc-ext, gssoc, hacktoberfest-accepted, level1

#32 corrected the UI Fault
  site/components/Process.js
Labels: gssoc-ext, gssoc, hacktoberfest-accepted, level1

#37 Added Issue and pr template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: gssoc-ext, gssoc, hacktoberfest-accepted, level1, hacktoberfest

#42 Add Hover Shadow Animation and Change Cursor Style on Details Cards
  site/components/DetailsCard.js
Labels: gssoc-ext, gssoc, hacktoberfest-accepted, level1, hacktoberfest

#48 @17 Created a contact us page frontend
  Learning.md
  package-lock.json
  site/components/Navbar.js
  site/pages/contact.js
  site/styles/contact.module.css
Labels: gssoc-ext, gssoc, hacktoberfest-accepted, level1, hacktoberfest

#54 Updated footer
  site/components/Footer.js
Labels: gssoc-ext, gssoc, hacktoberfest-accepted, level1, hacktoberfest

#27 Added missing icons for both login and register page and also added toggle feature
  site/pages/apply.js
  site/pages/login.js
Labels: gssoc-ext, gssoc, hacktoberfest-accepted, level1, hacktoberfest

#78 Added automated greetings bot
  .github/workflow/greetings.yml
Labels: gssoc-ext, gssoc, hacktoberfest-accepted, level1, hacktoberfest

#49 Fixing Inconsistent Box Sizes in the "How to Join BioTree" Section
  site/components/Process.js
  site/package-lock.json
  site/package.json
Labels: gssoc-ext, gssoc, hacktoberfest-accepted, level1, hacktoberfest

#88 Change in UI of Features
  site/components/DetailsCard.js
Labels: gssoc-ext, gssoc, hacktoberfest-accepted, level1, hacktoberfest

#33 Fixed bug:navbar Active link
  site/components/Navbar.js
Labels: gssoc-ext, gssoc, hacktoberfest-accepted, level1, hacktoberfest

#92 Update and redesign page buttons
  site/components/Navbar.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#103 Enhanced Card Shadows and Button Hover Effects
  site/components/Footer.js
  site/components/Process.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#107 Feat : Upgraded the "Download the App from" Part
  site/components/Footer.js
  site/src/Assets/apple-logo-svgrepo-com.svg
  site/src/Assets/playstore-svgrepo-com.svg
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#110 Created A Donation Page
  donation/button.html
  donation/main.html
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#112 input-border-fix
  site/pages/apply.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#113 Fixed the focus border and add cursor pointer in labels
  site/pages/apply.js
  site/styles/apply.module.css
  site/styles/globals.css
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#114 FIX : nav bar -> moved login element to right end
  site/components/Navbar.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#123 added all status code in responses
  server/controllers/auth.js
  server/controllers/dashboard.js
  server/controllers/getUserData.js
  server/controllers/loadLinks.js
  server/controllers/loadSocials.js
  server/controllers/saveLinks.js
  server/controllers/saveSocials.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#133 Add Hover Effect to FAQ Cards
  site/components/Faq.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#140 Modified README.md file and Contributing.md file.
  CONTRIBUTING.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#143 Add Hover Effects to BioTree Process Steps
  site/components/Process.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#147 Add feature: Enhanced the FAQ section
  site/components/Faq.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#146 improved navbar
  site/components/Navbar.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#150 Responsive Issue of Content page Fixed
  site/pages/contact.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#195 Add Google Sign-In feature
  server/auth.js
  server/index.js
  site/components/Navbar.js
  site/pages/apply.js
  site/pages/login.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#299 contactpage
  site/pages/contact.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#332 Added top to scroll button
  site/pages/_app.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#30 making top navbar fixed
  site/styles/globals.css
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#156 Added Scroll to top button
  site/components/ScrollToTopButton.js
  site/pages/_app.js
  site/styles/scrollToTopButton.css
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#241 Dynamically Update Copyright Year in Footer
  site/components/Footer.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#240 Issue #229-Fix FAQ UI and added feature toggle functionality on mobile devices
  site/components/Faq.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#231 Add feature: Scoll down button
  CONTRIBUTING.md
  package-lock.json
  site/package-lock.json
  site/package.json
  site/pages/index.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#216 Make Contact page responsive
  site/pages/contact.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#214 Added Footer Social Media icons of the website along with Hover animation.
  site/components/Footer.js
  site/tailwind.config.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#207 Added the Contributors Page
  site/components/Navbar.js
  site/pages/contributor.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#205 Navbar fix
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflow/greetings.yml
  Learning.md
  README.md
  package-lock.json
  site/components/DetailsCard.js
  site/components/Footer.js
  site/components/Navbar.js
  site/components/Process.js
  site/package-lock.json
  site/package.json
  site/pages/apply.js
  site/pages/contact.js
  site/pages/login.js
  site/styles/contact.module.css
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#244 fix footer bug
  site/components/Footer.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest
